use CSE_3B_320

--LAB:4 
--A 
ALTER TABLE DEPOSIT ADD CITY VARCHAR(20), PINCODE INT 

ALTER TABLE DEPOSIT ALTER COLUMN CNAME VARCHAR(35)

ALTER TABLE DEPOSIT ALTER COLUMN AMOUNT INT

EXEC sp_rename 'DEPOSIT.ACTNO','ANO'

ALTER TABLE DEPOSIT DROP COLUMN CITY

EXEC sp_rename 'DEPOSIT','DEPOSIT_DETAILS'


--B
EXEC sp_rename 'DEPOSIT_DETAILS.ADATE','AOPENDATE'

ALTER TABLE DEPOSIT_DETAILS DROP COLUMN	 AOPENDATE	

EXEC sp_rename 'DEPOSIT_DETAILS.CNAME','CUSTOMERNAME'


--C
CREATE TABLE STUDENT_DETAILS(
ENROLLMENT_NO VARCHAR(20),
NAME VARCHAR(25),
CPI DECIMAL(5,2),
BIRTHDATE DATETIME
)


ALTER TABLE STUDENT_DETAILS ADD CITY VARCHAR(20) NOT NULL , BACKLOG INT

ALTER TABLE STUDENT_DETAILS ALTER COLUMN NAME VARCHAR(35)

ALTER TABLE STUDENT_DETAILS ALTER COLUMN CPI INT

EXEC sp_rename 'STUDENT_DETAILS.ENROLLMENT_NO','ENO'

ALTER TABLE STUDENT_DETAILS DROP COLUMN	CITY

EXEC sp_rename 'STUDENT_DETAILS','STUDENT_MASTER'


--PART 2 
--A

DELETE FROM DEPOSIT_DETAILS WHERE AMOUNT > 4000

DELETE FROM DEPOSIT_DETAILS WHERE BNAME = 'CHANDI BRANCH'

DELETE FROM DEPOSIT_DETAILS WHERE ANO > 105

TRUNCATE TABLE DEPOSIT_DETAILS

DROP TABLE DEPOSIT_DETAILS

--B
CREATE TABLE EMPLOYEE_MASTER(
EMPNO INT,
EMPNAME VARCHAR(25),
JOININGDATE DATETIME,
SALARY DECIMAL(8,2),
CITY VARCHAR(20)
)

INSERT INTO EMPLOYEE_MASTER VALUES(101,'Keyur','5-JAN-02',12000.00,' Rajkot')
INSERT INTO EMPLOYEE_MASTER VALUES(102,'Hardik','15-FEB-04',14000.00,'Ahmedabad')
INSERT INTO EMPLOYEE_MASTER VALUES(103,'Kajal','14-MAR-06',15000.00,'Baroda')
INSERT INTO EMPLOYEE_MASTER VALUES(104,'Bhoomi','23-JUN-05 ',12500.00,'Ahmedabad')
INSERT INTO EMPLOYEE_MASTER VALUES(105,'Harmit','15-FEB-04',14000.00,'Rajkot')
INSERT INTO EMPLOYEE_MASTER VALUES(106,'Mitesh','25-SEP-01',5000.00,'Jamnagar')
INSERT INTO EMPLOYEE_MASTER VALUES(107,'Meera',NULL,7000.00,'Morbi')
INSERT INTO EMPLOYEE_MASTER VALUES(108,'Kishan','6-FEB-03',10000.00,NULL)


DELETE FROM EMPLOYEE_MASTER WHERE SALARY > 14000

DELETE FROM EMPLOYEE_MASTER WHERE CITY = 'RAJKOT'

DELETE FROM EMPLOYEE_MASTER WHERE JOININGDATE > '1-JAN-2007'

DELETE FROM EMPLOYEE_MASTER WHERE JOININGDATE IS NULL AND EMPNAME IS NOT NULL
