CREATE TABLE CRICKET(
NAME VARCHAR(25),
CITY VARCHAR(25),
AGE INT
)

INSERT INTO CRICKET
VALUES('SACHIN TENDULKAR','MUMBAI',30)

INSERT INTO CRICKET
VALUES('RAHUL DRAVID','BOMBAY',35)

INSERT INTO CRICKET
VALUES('M.S. DOHNI','JARKHAND',31)

INSERT INTO CRICKET
VALUES('SURESH RAINA','GUJRAT',30)

SELECT * FROM CRICKET

SELECT * INTO WORLDCUP FROM CRICKET

SELECT NAME,CITY INTO T20 FROM CRICKET WHERE 1=0

SELECT * INTO IPL FROM CRICKET WHERE 1=0

CREATE TABLE EMPLOYEE (
NAME VARCHAR(25),
CITY VARCHAR(25),
AGE INT
)

INSERT INTO EMPLOYEE
VALUES('JAY PATEL','RAJKOT',30)

INSERT INTO EMPLOYEE
VALUES('RAHUL DAVE','BARODA',35)

INSERT INTO EMPLOYEE
VALUES('JEET PATEL','SURAT',31)

INSERT INTO EMPLOYEE
VALUES('VIJAY RAVAL','RAJKOT',30)

SELECT * INTO Employee_detail FROM EMPLOYEE

SELECT NAME,CITY INTO Employee_data FROM EMPLOYEE WHERE 1=0

SELECT * INTO Employee_info FROM EMPLOYEE WHERE 1=0

INSERT INTO Employee_info
SELECT NAME,CITY,AGE FROM EMPLOYEE WHERE CITY='RAJKOT' OR AGE > 32

SELECT * FROM Employee_info

SELECT * FROM DEPOSIT

--A

UPDATE DEPOSIT
SET AMOUNT=5000 WHERE AMOUNT = 3000

UPDATE BORROW 
SET BNAME = 'C.G. ROAD' WHERE CNAME='ANIL'

UPDATE DEPOSIT
SET ACTNO = 111,AMOUNT=5000 WHERE CNAME='SANDIP'

UPDATE DEPOSIT
SET AMOUNT=7000 WHERE CNAME = 'KRANTI'

UPDATE BRANCH
SET BNAME ='ANDHERI WEST' WHERE BNAME='ANDHERI'

UPDATE DEPOSIT
SET BNAME = 'NEHRU PALACE' WHERE CNAME='MEHUL'

UPDATE DEPOSIT
SET AMOUNT=5000 WHERE ACTNO>=103 AND ACTNO<=107

UPDATE DEPOSIT 
SET ADATE='01-MAR-95' WHERE CNAME='ANIL'

UPDATE DEPOSIT
SET AMOUNT=10000 WHERE CNAME='MINU'

UPDATE DEPOSIT
SET ADATE='01-MAR-96',AMOUNT=5000 WHERE CNAME='PRAMOD'

--B
UPDATE BORROW
SET AMOUNT= (AMOUNT*0.1) + AMOUNT

UPDATE DEPOSIT
SET AMOUNT= (AMOUNT*0.2) + AMOUNT

--C
UPDATE BORROW
SET AMOUNT = NULL WHERE LOANNO=321

UPDATE BORROW
SET BNAME = NULL WHERE CNAME='KRANTI'

SELECT CNAME FROM BORROW WHERE AMOUNT IS NULL

SELECT CNAME FROM BORROW WHERE BNAME IS NULL

UPDATE BORROW
SET BNAME='VRCE',AMOUNT=5000,CNAME='DARSHAN' WHERE LOANNO=481

UPDATE DEPOSIT
SET ADATE='01-JAN-21' WHERE AMOUNT<2000

UPDATE DEPOSIT
SET ADATE=NULL,BNAME='ANDHERI' WHERE ACTNO=110
